---
name: geode

director_uuid: <%= `bosh status --uuid` %>

releases:
- name: geode
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: locator
  azs: [az1]
  instances: 2
  jobs:
  - name: locator
    release: geode
    properties: {}
  vm_type: small
  stemcell: ubuntu
  persistent_disk_type: '10240'
  networks:
  - name: ert
- name: server
  azs: [az1]
  instances: 3
  jobs:
  - name: server
    release: geode
    properties: {}
  vm_type: small
  stemcell: ubuntu
  persistent_disk_type: '10240'
  networks:
  - name: ert