---
name: geode

director_uuid: <%= `bosh status --uuid` %>

releases:
- name: geode
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: locator
  azs: [z1]
  instances: 1
  jobs:
  - name: locator
    release: geode
    properties: {}
  vm_type: default
  stemcell: ubuntu
  persistent_disk_type: default
  networks:
  - name: default
- name: server
  azs: [z1]
  instances: 3
  jobs:
  - name: server
    release: geode
    properties: {}
  vm_type: default
  stemcell: ubuntu
  persistent_disk_type: default
  networks:
  - name: default